/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.usi.inf.sa2.CookieCrumbles;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author alexm
 */
public class ParticleEmitter {
    private int particleCount;
     double originX;
     double originY;
    private ArrayList particleList;
    Rectangle boundingBox;
    CCWall wall;
    CCWall wall2;
    CCWall wall3;
    CCWall wall4;
    
 
    /**
     *
     * @param originX
     * @param originY
     * @param particleCount
     */
    public ParticleEmitter(double originX, double originY, int particleCount){
        this.particleCount = particleCount;
        this.originX = originX;
        this.originY = originY;
        boundingBox = new Rectangle((int) originX,(int) originY,35,35);
        particleList  = new ArrayList();    
        wall2 = new CCWall (-900,-300, 300, 3.14/2);
        wall = new CCWall(-500, -400, 300 ,  3.14);
        wall3 = new CCWall(-500, 100, 300 ,  3.14);
        wall4 = new CCWall(-700, -200, 200 ,  3.14/2+0.223);
    }
   
     /**
     *
     * @return
     */
    public double lengthRandomizer() {
        Random rand = new Random();
        double randomNum = rand.nextInt(100) + 1;
        return randomNum;
    }
     
     public Rectangle getBoundingBox(){
         return boundingBox;
         
     }
     
     public void setBoundingBox(Rectangle rect){
         boundingBox = rect; 
     }
    
     
    /**
     *
     * @return
     */
    public double directionRandomizer() {
        Random rand = new Random();
        double min = 0;
        double max = 3.14*2;  //180 degreees!!
        double randomNum = min + (max - min) * rand.nextDouble();
        
        return randomNum;
    }
    
    public double getOriginX(){
        return originX;
    }
    
    /**
     *
     * @return
     */
    public double getOriginY(){
        return originY;
    }
    
    /**
     *
     * @param shiftXBy
     */
    public void setOriginX(double shiftXBy){
        originX = shiftXBy;
    }
    
    public void setOriginY ( double shiftYBy){
        originY = shiftYBy;
    }
    
    /**
     *
     * @param hi
     */
    public void setParticleList(ArrayList hi){
        particleList = hi;
    }
    
    
    /**
     *
     * @return
     */
    public ArrayList getParticleList(){
        return particleList;
    } 
    /*
     * Sets a number of particles generated by Particle 
     * emitter object.
     */
    public void setParticleCount( final int newCount){
        particleCount = newCount;
    }
   
    
    /**
     *
     * @return
     */
    public int getParticleCount() {
        return particleCount;
    }
    
   
    
   
    /**
     *
     * @param gr
     */
    public void recalculate(final Graphics gr){
        Graphics2D g = (Graphics2D) gr;
        wall.drawWall(g);
        
        wall2.drawWall(g);
        wall3.drawWall(g);
        wall4.drawWall(g);
        for (int i = 0; i <6; i++) {
            
        
        Particle myparticle = new Particle(originX, originY, originX ,originY, directionRandomizer(), /// In radians
                0, 90, 
                1, 1);
        Shape particleNew = new Rectangle((int) originX,
                    (int) originY, 5,5);
            myparticle.setParticleRect(particleNew);
        particleList.add(myparticle);
        
        }
        for (int i = 0; i < particleList.size(); i++) {
            
            
            Particle part = (Particle) particleList.get(i);
            Shape wallLine = wall.getWallShape();
            //System.out.println("" + part.getEmitterOriginX()+" " + part.getEmitterOriginY());
            Shape wallline2 = wall2.getWallShape();
            Shape wallline3 = wall3.getWallShape();
            Shape wallline4 = wall4.getWallShape();
            Shape particleRect2 = part.getParticleRect();
            Rectangle2D particleRect = particleRect2.getBounds2D();
            
            
            
            if (wallLine.intersects(particleRect)){ 
//                double x =part.getPositionReset().getX();
//                double y = part.getPositionReset().getY();
//                double len = part.getPositionReset().getLength();
//                double dir = part.getPosition().getAzimuth();
//                CCVector reset = new CCVector(new CartesianCoordinate(x, y), 
//                        new PolarCoordinate(dir, len));
//                
                
                double newOriginX =  part.positionGetX() + part.getEmitterOriginX() ;
                double newOriginY =  part.positionGetY() + part.getEmitterOriginY() ;
                part.setOriginX(newOriginX);
                part.setOriginY(newOriginY);
                CCVector reflected = wall.calculateReflected(part.getPositionReset(), newOriginX, newOriginY);
                part.setPosition(reflected);
                
                g.setPaint(Color.BLACK);
                part.setNewPosition();
                Shape particleNew = new Rectangle((int) part.getEmitterOriginX()  ,
                    (int)part.getEmitterOriginY() , 5,5);
                
                part.setParticleRect(particleNew);
                //part.setParticleReset(reflected);
                g.draw(particleNew);
                continue;
//                CCVector reset = part.getPositionReset();
//            reset.setAzi(part.getPosition().getAzimuth());
//            part.setParticleReset(reset);
                
                
                
            }
            
            
            
            //// TO DELETE LATER MOTHERFUCKA
            
            if (wallline2.intersects(particleRect)){ 
//                double x =part.getPositionReset().getX();
//                double y = part.getPositionReset().getY();
//                double len = part.getPositionReset().getLength();
//                double dir = part.getPosition().getAzimuth();
//                CCVector reset = new CCVector(new CartesianCoordinate(x, y), 
//                        new PolarCoordinate(dir, len));
//                
                
                double newOriginX =  part.positionGetX() + part.getEmitterOriginX() ;
                double newOriginY =  part.positionGetY() + part.getEmitterOriginY() ;
                part.setOriginX(newOriginX);
                part.setOriginY(newOriginY);
                CCVector reflected = wall2.calculateReflected(part.getPositionReset(), newOriginX, newOriginY);
                part.setPosition(reflected);
                
                g.setPaint(Color.BLACK);
                part.setNewPosition();
                Shape particleNew = new Rectangle((int) part.getEmitterOriginX()  ,
                    (int)part.getEmitterOriginY() , 5,5);
                
                part.setParticleRect(particleNew);
                //part.setParticleReset(reflected);
                g.draw(particleNew);
                continue;
//                CCVector reset = part.getPositionReset();
//            reset.setAzi(part.getPosition().getAzimuth());
//            part.setParticleReset(reset);
                
                
                
            }
            
            
            if (wallline3.intersects(particleRect)){ 
//                double x =part.getPositionReset().getX();
//                double y = part.getPositionReset().getY();
//                double len = part.getPositionReset().getLength();
//                double dir = part.getPosition().getAzimuth();
//                CCVector reset = new CCVector(new CartesianCoordinate(x, y), 
//                        new PolarCoordinate(dir, len));
//                
                
                double newOriginX =  part.positionGetX() + part.getEmitterOriginX() ;
                double newOriginY =  part.positionGetY() + part.getEmitterOriginY() ;
                part.setOriginX(newOriginX);
                part.setOriginY(newOriginY);
                CCVector reflected = wall3.calculateReflected(part.getPositionReset(), newOriginX, newOriginY);
                part.setPosition(reflected);
                
                g.setPaint(Color.BLACK);
                part.setNewPosition();
                Shape particleNew = new Rectangle((int) part.getEmitterOriginX()  ,
                    (int)part.getEmitterOriginY() , 5,5);
                
                part.setParticleRect(particleNew);
                //part.setParticleReset(reflected);
                g.draw(particleNew);
                continue;
//                CCVector reset = part.getPositionReset();
//            reset.setAzi(part.getPosition().getAzimuth());
//            part.setParticleReset(reset);
                
                
                
            }
            
            if (wallline4.intersects(particleRect)){ 
//                double x =part.getPositionReset().getX();
//                double y = part.getPositionReset().getY();
//                double len = part.getPositionReset().getLength();
//                double dir = part.getPosition().getAzimuth();
//                CCVector reset = new CCVector(new CartesianCoordinate(x, y), 
//                        new PolarCoordinate(dir, len));
//                
                
                double newOriginX =  part.positionGetX() + part.getEmitterOriginX() ;
                double newOriginY =  part.positionGetY() + part.getEmitterOriginY() ;
                part.setOriginX(newOriginX);
                part.setOriginY(newOriginY);
                CCVector reflected = wall4.calculateReflected(part.getPositionReset(), newOriginX, newOriginY);
                part.setPosition(reflected);
                
                g.setPaint(Color.BLACK);
                part.setNewPosition();
                Shape particleNew = new Rectangle((int) part.getEmitterOriginX()  ,
                    (int)part.getEmitterOriginY() , 5,5);
                
                part.setParticleRect(particleNew);
                //part.setParticleReset(reflected);
                g.draw(particleNew);
                continue;
//                CCVector reset = part.getPositionReset();
//            reset.setAzi(part.getPosition().getAzimuth());
//            part.setParticleReset(reset);
                
                
                
            }
            
            
            
            
            
            
            
            
            
            /////////// TILL HERE 
            
            
            
            
            int lifetime = part.getLifetime();
            lifetime++;
            part.setLifetime(lifetime);
            part.setNewPosition();
            double x = part.positionGetX();
            double y = part.positionGetY();
            g.setPaint(Color.BLACK);
            //// TEST 
           
            
            
            CCVector reset = part.getPositionReset();
           reset.setAzi(part.getPosition().getAzimuth());
            part.setParticleReset(reset);
            
            Shape particleNew = new Rectangle((int) part.getEmitterOriginX() + (int)x,
                    (int)part.getEmitterOriginY() +(int)y, 5,5);
            part.setParticleRect(particleNew);
            g.draw(particleNew);
            if (lifetime > 2000) {
                particleList.remove(part);
                part = null;
                
            }
            //System.out.println(""+ part.getPosition().getAzimuth() + ","+ part.getPositionReset().getAzimuth());
            
            
            }
        
                
        
           
    
}

}
